ALTER TABLE hr_tickets ADD COLUMN IF NOT EXISTS csat_rating   SMALLINT CHECK (csat_rating BETWEEN 1 AND 5);
ALTER TABLE hr_tickets ADD COLUMN IF NOT EXISTS csat_comment  TEXT;
ALTER TABLE hr_tickets ADD COLUMN IF NOT EXISTS csat_rated_at TIMESTAMPTZ;